import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import './globals.css'
import Header from './(components)/Header'
import Footer from './(components)/Footer'
import Provider from '@/utils/QueryProvider'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Audiophile E-commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Provider>
          <Header />
          {children}
        </Provider>
        <Footer />
      </body>
    </html>
  )
}
